### PR TITLE
fix typed data signing

### PR DESCRIPTION
**Pull request by cruzdanilo**
fixes a critical issue that is preventing typed data signing of any kind.

### CODE REVIEW

**Comment by bbondy** [comment]
Hi @cruzdanilo Do you have a site that's used in the wild that uses typed data signing?

**Comment by cruzdanilo** [comment]
@bbondy https://zed.run/

**Comment by bbondy** [comment]
Does MM also need this fix? Seems like they don't have it.
https://github.com/MetaMask/eth-ledger-bridge-keyring/blob/c3c0e01de5893d5c9731c256301b138deb727704/index.js#L401

By the way this wallet is deprecated as of less than 2 weeks from now. You'll still be able to use it but the new Brave Wallet replaces it and doesn't use this dep. Do you think this is important to include in the old wallet?

**Comment by cruzdanilo** [comment]
@bbondy mm is not using the same method. the breaking change was introduced here: https://github.com/brave/eth-ledger-bridge-keyring/commit/6db82c15435f9ae47dadbc1fc19586552a7044eb

does the new wallet work with `signTypedData`+ledger? where can i find it for testing?
this issue is blocking brave+ledger users on our application.

**Comment by bbondy** [comment]
OK thanks, we'll also need to update the dep here https://github.com/brave/ethereum-remote-client/blob/master/package.json#L107 if you don't mind after this is merged.

> does the new wallet work with signTypedData+ledger? where can i find it for testing?
this issue is blocking brave+ledger users on our application.

Signing works, but not yet with typed data.

**Comment by bbondy** [comment]
You can use Brave Nightly to test out the new wallet, you'll still be able to use the old wallet if you need to in the meantime.

**Review by bbondy — APPROVED** [review]

**Pull request merged**
